org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=gbaminecraft
mod_name=Fantastic Boy Advance
mod_license=MIT
mod_version=1.5.8
mod_authors=GBAMod Team
mod_description=Fantastic Boy Advance: emula juegos de Game Boy Advance dentro de Minecraft con un emulador escrito en Java. Sosten el item, clic derecho y juega.
