modLoader = "javafml"
loaderVersion = "[47,)"
license = "UNLICENSED"

[[mods]]
modId = "fantasticnametags"
version = "1.0.1"
displayName = "Fantastic Nametags"
description = "Sube las lineas del nametag (nombre y rangos) por encima de la cabeza. Se configura desde el server y se sincroniza a todos los clientes."

[[dependencies.fantasticnametags]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fantasticnametags]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
