# Gradle / JVM
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=invhistory
mod_name=InvHistory
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.arthurleray.invhistory
mod_authors=ArthurLERAY
mod_description=Server-side inventory history tracking for administrators (port a Forge 1.20.1).

## Library versions
snakeyaml_version=2.2
